services:
  db:
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning 
    ports:
      - "5432:5432"
  backend:
    image: bjornmagnussonconsid/spring-boot-learning:${BACKEND_VERSION:-latest}
    ports:
      - "${BACKEND_PORT:-8888}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/learning
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ORIGINS_ALLOWED: "http://localhost:${BACKEND_PORT:-8000}"
  frontend:
    image: bjornmagnussonconsid/angular-learning:${FRONTEND_VERSION:-latest}
    ports:
      - "${BACKEND_PORT:-8000}:8080"
    environment:
      API_URL: http://localhost:${BACKEND_PORT:-8888}
    depends_on:
      - backend
    entrypoint: launcher
    command: "\"envsubst '$${API_URL}' < /workspace/dist/angular-learning/assets/config.teml.json > /workspace/dist/angular-learning/assets/config.json && /cnb/process/web\""