name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bump: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:        
        fetch-depth: 0

    - name: Next version
      uses: madhead/semver-utils@latest
      id: version
      with:
        version: ${{ github.ref_name }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Bump version
      run: npm version patch --no-git-tag-version

    - name: Setup git user
      uses: snow-actions/git-config-user@v1.0.0

    - name: Commit version update
      run: |
        git add package.json
        git commit -m "Bump version to ${{ steps.version.outputs.inc-patch }}-SNAPSHOT"

    - name: Push to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main